export const PrecedentsSchema = {
  collection: 'precedents',
  label: 'Precedents',
  primaryKey: 'id',
  core: true,
  fields: {
    id: 'string',
    title: 'string',
    citation: 'string',
    neutral_citation: 'string',
    court: 'string',
    bench: 'string',
    judges: 'array',
    case_number: 'string',
    case_type: 'string',
    jurisdiction: 'string',
    stage: 'string',
    source: 'string',
    status: 'string',
    plaintiff: 'string',
    defendant: 'string',
    type_of_proceeding: 'string',
    nature_of_dispute: 'string',
    act: 'string',
    provisions: 'array',
    headnotes: 'text',
    summary: 'text',
    full_text: 'text',
    ratio_decidendi: 'text',
    obiter_dicta: 'text',
    key_findings: 'text',
    legal_principle: 'string',
    category: 'string',
    practice_area: 'string',
    authority_level: 'string',
    precedential_value: 'string',
    tags: 'array',
    keywords: 'array',
    cases_cited: 'array',
    acts_cited: 'array',
    overruled_by: 'string',
    followed_by: 'string',
    date: 'datetime',
    judgment_date: 'datetime',
    created_at: 'datetime',
    updated_at: 'datetime',
    created_by: 'string',
    modified_by: 'string',
    favourite: 'boolean',
    pinned: 'boolean',
  },
  required: ['title', 'citation'],
  defaults: {
    status: 'Active',
    tags: [],
    keywords: [],
    provisions: [],
    judges: [],
    cases_cited: [],
    acts_cited: [],
    favourite: false,
    pinned: false,
  },
  relations: [],
  indexes: ['citation', 'court', 'case_type', 'jurisdiction', 'category', 'status', 'authority_level'],
};
