// SchemaCompiler — turns the universal schema descriptors into provider-specific
// artifacts. This is the SINGLE SOURCE OF TRUTH for "what a table/collection looks
// like" on each backend; no schema shape is duplicated anywhere else (the
// migration strategies and the installer both consume this).
//
// It imports NO database SDK and runs in the browser: it EMITS artifacts (SQL
// text, rule strings, mongoose-definition source, index specs). Executing those
// artifacts is the installer's job, using each provider's browser-reachable API.
import { listSchemas, getSchema, SCHEMA_VERSION } from './index.js';

// ---- type maps ------------------------------------------------------------
const PG = { string: 'text', number: 'numeric', boolean: 'boolean', datetime: 'timestamptz', array: 'jsonb', object: 'jsonb', json: 'jsonb' };
const MONGOOSE = { string: 'String', number: 'Number', boolean: 'Boolean', datetime: 'Date', array: 'Array', object: 'Object', json: 'Object' };
const BSON = { string: 'string', number: 'number', boolean: 'bool', datetime: 'date', array: 'array', object: 'object', json: 'object' };
const FS = { string: 'string', number: 'number', boolean: 'bool', datetime: 'timestamp', array: 'list', object: 'map', json: 'map' };

const q = (id) => `"${id}"`;

// ---- Supabase / Postgres --------------------------------------------------
function toSupabase(schema) {
  const cols = Object.entries(schema.fields).map(([name, type]) => {
    if (name === schema.primaryKey) return `  ${q(name)} text primary key`;
    return `  ${q(name)} ${PG[type] || 'text'}`;
  });
  const createTable = `create table if not exists ${q(schema.collection)} (\n${cols.join(',\n')}\n);`;
  const createIndexes = (schema.indexes || []).map(
    (f) => `create index if not exists ${`idx_${schema.collection}_${f}`} on ${q(schema.collection)} (${q(f)});`
  );
  // Additive column diff against columns that already exist on the backend.
  const alterTable = (existingColumns = []) =>
    Object.entries(schema.fields)
      .filter(([name]) => !existingColumns.includes(name))
      .map(([name, type]) => `alter table ${q(schema.collection)} add column if not exists ${q(name)} ${name === schema.primaryKey ? 'text' : (PG[type] || 'text')};`);
  return { provider: 'supabase', collection: schema.collection, createTable, createIndexes, alterTable, sql: [createTable, ...createIndexes].join('\n') };
}

// ---- Firebase / Firestore -------------------------------------------------
function toFirebase(schema) {
  // Firestore is schemaless; we emit a validation-rule block and index defs.
  const checks = Object.entries(schema.fields)
    .filter(([name]) => name !== schema.primaryKey)
    .map(([name, type]) => {
      const t = FS[type] || 'string';
      const present = `(!('${name}' in request.resource.data) || request.resource.data.${name} == null || request.resource.data.${name} is ${t})`;
      return `        ${present}`;
    });
  const required = (schema.required || []).map((f) => `        '${f}' in request.resource.data`);
  const rule = [
    `    match /${schema.collection}/{docId} {`,
    '      allow read: if true;',
    '      allow write: if',
    [...required, ...checks].join(' &&\n') || '        true',
    '      ;',
    '    }',
  ].join('\n');
  const indexes = (schema.indexes || []).map((f) => ({
    collectionGroup: schema.collection,
    queryScope: 'COLLECTION',
    fields: [{ fieldPath: f, order: 'ASCENDING' }],
  }));
  return {
    provider: 'firebase',
    collection: schema.collection,
    definition: { collection: schema.collection, fields: schema.fields, required: schema.required || [] },
    rules: rule,
    indexes,
  };
}

// ---- MongoDB --------------------------------------------------------------
function toMongo(schema) {
  // mongoose is Node-only — we emit DEFINITION SOURCE (a string) plus a portable
  // $jsonSchema validator and index specs the Atlas Data API/back-end can apply.
  const defLines = Object.entries(schema.fields).map(([name, type]) => {
    const mt = MONGOOSE[type] || 'String';
    const idx = (schema.indexes || []).includes(name) ? ', index: true' : '';
    const uniq = name === schema.primaryKey ? ', unique: true' : '';
    return `  ${name}: { type: ${mt}${idx}${uniq} }`;
  });
  const mongooseDefinition =
    `// generated by SchemaCompiler — collection: ${schema.collection}\n` +
    `const ${schema.collection}Schema = new mongoose.Schema({\n${defLines.join(',\n')}\n}, { collection: '${schema.collection}', strict: false });`;

  const properties = {};
  Object.entries(schema.fields).forEach(([name, type]) => { properties[name] = { bsonType: BSON[type] || 'string' }; });
  const jsonSchema = {
    $jsonSchema: {
      bsonType: 'object',
      required: schema.required || [],
      properties,
    },
  };
  const indexes = [
    { key: { [schema.primaryKey]: 1 }, name: `${schema.primaryKey}_unique`, unique: true },
    ...(schema.indexes || []).map((f) => ({ key: { [f]: 1 }, name: `${f}_idx` })),
  ];
  return { provider: 'mongodb', collection: schema.collection, mongooseDefinition, jsonSchema, indexes };
}

// ---- Local ----------------------------------------------------------------
function toLocal(schema) {
  return {
    provider: 'local',
    collection: schema.collection,
    init: { collection: schema.collection, fields: Object.keys(schema.fields), defaults: schema.defaults || {} },
  };
}

// ---- System infrastructure SQL (emitted before user DDL) ------------------
function systemSql(provider) {
  if (provider !== 'supabase') return null;
  return [
    '-- ============================================================',
    '-- SYSTEM INFRASTRUCTURE',
    '-- ============================================================',
    '',
    '-- exec_sql RPC — allows browser clients to execute DDL via PostgREST',
    'create or replace function exec_sql(sql text)',
    'returns void',
    'language plpgsql',
    'security definer',
    'as $$',
    'begin',
    '  execute sql;',
    'end;',
    '$$;',
    '',
    'grant execute on function exec_sql(text) to anon;',
    'grant execute on function exec_sql(text) to authenticated;',
    '',
    '-- schema_registry — tracks schema versions & migrations applied',
    'create table if not exists schema_registry (',
    '  id text primary key default gen_random_uuid()::text,',
    '  version integer not null default 0,',
    '  description text,',
    '  checksum text,',
    '  applied_at timestamptz default now(),',
    '  applied_by text default current_user',
    ');',
    '',
    '-- entity_registry — registered entity definitions',
    'create table if not exists entity_registry (',
    '  id text primary key default gen_random_uuid()::text,',
    '  name text not null unique,',
    '  label text,',
    '  table_name text not null,',
    '  primary_key text default \'id\',',
    '  core boolean default false,',
    '  fields jsonb default \'{}\'::jsonb,',
    '  indexes jsonb default \'{}\'::jsonb,',
    '  created_at timestamptz default now(),',
    '  updated_at timestamptz default now()',
    ');',
    '',
    '-- field_registry — field-level metadata per entity',
    'create table if not exists field_registry (',
    '  id text primary key default gen_random_uuid()::text,',
    '  entity text not null,',
    '  field_name text not null,',
    '  field_type text not null,',
    '  required boolean default false,',
    '  unique_field boolean default false,',
    '  default_value text,',
    '  created_at timestamptz default now()',
    ');',
    '',
    '-- provider_registry — database provider configuration',
    'create table if not exists provider_registry (',
    '  id text primary key default gen_random_uuid()::text,',
    '  provider_type text not null,',
    '  label text,',
    '  config jsonb default \'{}\'::jsonb,',
    '  active boolean default true,',
    '  connected_at timestamptz,',
    '  created_at timestamptz default now(),',
    '  updated_at timestamptz default now()',
    ');',
    '',
    '-- migration_registry — audit log of all schema migrations',
    'create table if not exists migration_registry (',
    '  id text primary key default gen_random_uuid()::text,',
    '  version integer not null,',
    '  description text,',
    '  sql_hash text,',
    '  applied_at timestamptz default now(),',
    '  duration_ms integer,',
    '  success boolean default true,',
    '  error text',
    ');',
    '',
    '-- id_registry + LX-ID sequence manager',
    '-- Generates LX-{ENTITY}-{SEQUENCE} business IDs natively in PostgreSQL',
    'create table if not exists id_registry (',
    '  entity text primary key,',
    '  prefix text not null,',
    '  sequence integer not null default 0,',
    '  created_at timestamptz default now(),',
    '  updated_at timestamptz default now()',
    ');',
    '',
    'create or replace function next_lx_id(p_entity text)',
    'returns text',
    'language plpgsql',
    'as $$',
    'declare',
    '  v_prefix text;',
    '  v_seq integer;',
    '  v_id text;',
    'begin',
    '  insert into id_registry (entity, prefix, sequence)',
    '  values (p_entity, upper(\'LX-\' || p_entity || \'-\'), 0)',
    '  on conflict (entity) do nothing;',
    '  update id_registry',
    '  set sequence = sequence + 1,',
    '      updated_at = now()',
    '  where entity = p_entity',
    '  returning prefix || lpad(sequence::text, 5, \'0\') into v_id;',
    '  return v_id;',
    'end;',
    '$$;',
    '',
    'grant execute on function next_lx_id(text) to anon;',
    'grant execute on function next_lx_id(text) to authenticated;',
    '',
    '-- Indexes for registry tables',
    'create index if not exists idx_field_registry_entity on field_registry (entity);',
    'create index if not exists idx_schema_registry_version on schema_registry (version);',
    'create index if not exists idx_migration_registry_version on migration_registry (version);',
    'create index if not exists idx_migration_registry_applied_at on migration_registry (applied_at);',
    'create index if not exists idx_provider_registry_active on provider_registry (active);',
  ].join('\n');
}

const COMPILERS = { supabase: toSupabase, firebase: toFirebase, mongodb: toMongo, local: toLocal };

export const SchemaCompiler = {
  // Compile one schema (by name or descriptor) for a provider.
  compile(provider, schemaOrName) {
    const schema = typeof schemaOrName === 'string' ? getSchema(schemaOrName) : schemaOrName;
    if (!schema) throw new Error(`Unknown schema: ${schemaOrName}`);
    const fn = COMPILERS[provider] || COMPILERS.local;
    return fn(schema);
  },

  // Compile every schema for a provider.
  compileAll(provider) {
    return listSchemas().map((s) => this.compile(provider, s));
  },

  // A single install script/bundle for a provider.
  installArtifact(provider) {
    const parts = this.compileAll(provider);
    if (provider === 'supabase') {
      const infra = systemSql(provider);
      const ddl = parts.map((p) => p.sql).join('\n\n');
      const grants = [
        '-- Grant permissions to anon and authenticated roles',
        'GRANT USAGE ON SCHEMA public TO anon;',
        'GRANT USAGE ON SCHEMA public TO authenticated;',
        '',
        'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO anon;',
        'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO authenticated;',
        '',
        'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO anon;',
        'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO authenticated;',
      ].join('\n');
      return { kind: 'sql', schemaVersion: SCHEMA_VERSION, text: [infra, ddl, grants].join('\n\n') };
    }
    if (provider === 'firebase') {
      return {
        kind: 'firebase',
        schemaVersion: SCHEMA_VERSION,
        rules: `rules_version = '2';\nservice cloud.firestore {\n  match /databases/{database}/documents {\n${parts.map((p) => p.rules).join('\n')}\n  }\n}`,
        indexes: { indexes: parts.flatMap((p) => p.indexes) },
      };
    }
    if (provider === 'mongodb') {
      return {
        kind: 'mongodb',
        schemaVersion: SCHEMA_VERSION,
        mongoose: parts.map((p) => p.mongooseDefinition).join('\n\n'),
        validators: Object.fromEntries(parts.map((p) => [p.collection, p.jsonSchema])),
        indexes: Object.fromEntries(parts.map((p) => [p.collection, p.indexes])),
      };
    }
    return { kind: 'local', schemaVersion: SCHEMA_VERSION, collections: parts.map((p) => p.init) };
  },
};

export default SchemaCompiler;
