// SchemaCompiler — turns the universal schema descriptors into provider-specific
// artifacts. This is the SINGLE SOURCE OF TRUTH for "what a table/collection looks
// like" on each backend; no schema shape is duplicated anywhere else (the
// migration strategies and the installer both consume this).
//
// It imports NO database SDK and runs in the browser: it EMITS artifacts (SQL
// text, rule strings, mongoose-definition source, index specs). Executing those
// artifacts is the installer's job, using each provider's browser-reachable API.
import { listSchemas, getSchema, SCHEMA_VERSION } from './index.js';

// ---- type maps ------------------------------------------------------------
const PG = { string: 'text', number: 'numeric', boolean: 'boolean', datetime: 'timestamptz', array: 'jsonb', object: 'jsonb', json: 'jsonb' };
const MONGOOSE = { string: 'String', number: 'Number', boolean: 'Boolean', datetime: 'Date', array: 'Array', object: 'Object', json: 'Object' };
const BSON = { string: 'string', number: 'number', boolean: 'bool', datetime: 'date', array: 'array', object: 'object', json: 'object' };
const FS = { string: 'string', number: 'number', boolean: 'bool', datetime: 'timestamp', array: 'list', object: 'map', json: 'map' };

const q = (id) => `"${id}"`;

// ---- Supabase / Postgres --------------------------------------------------
function toSupabase(schema) {
  const cols = Object.entries(schema.fields).map(([name, type]) => {
    if (name === schema.primaryKey) return `  ${q(name)} text primary key`;
    return `  ${q(name)} ${PG[type] || 'text'}`;
  });
  const createTable = `create table if not exists ${q(schema.collection)} (\n${cols.join(',\n')}\n);`;
  const createIndexes = (schema.indexes || []).map(
    (f) => `create index if not exists ${`idx_${schema.collection}_${f}`} on ${q(schema.collection)} (${q(f)});`
  );
  // Additive column diff against columns that already exist on the backend.
  const alterTable = (existingColumns = []) =>
    Object.entries(schema.fields)
      .filter(([name]) => !existingColumns.includes(name))
      .map(([name, type]) => `alter table ${q(schema.collection)} add column if not exists ${q(name)} ${name === schema.primaryKey ? 'text' : (PG[type] || 'text')};`);
  return { provider: 'supabase', collection: schema.collection, createTable, createIndexes, alterTable, sql: [createTable, ...createIndexes].join('\n') };
}

// ---- Firebase / Firestore -------------------------------------------------
function toFirebase(schema) {
  // Firestore is schemaless; we emit a validation-rule block and index defs.
  const checks = Object.entries(schema.fields)
    .filter(([name]) => name !== schema.primaryKey)
    .map(([name, type]) => {
      const t = FS[type] || 'string';
      const present = `(!('${name}' in request.resource.data) || request.resource.data.${name} == null || request.resource.data.${name} is ${t})`;
      return `        ${present}`;
    });
  const required = (schema.required || []).map((f) => `        '${f}' in request.resource.data`);
  const rule = [
    `    match /${schema.collection}/{docId} {`,
    '      allow read: if true;',
    '      allow write: if',
    [...required, ...checks].join(' &&\n') || '        true',
    '      ;',
    '    }',
  ].join('\n');
  const indexes = (schema.indexes || []).map((f) => ({
    collectionGroup: schema.collection,
    queryScope: 'COLLECTION',
    fields: [{ fieldPath: f, order: 'ASCENDING' }],
  }));
  return {
    provider: 'firebase',
    collection: schema.collection,
    definition: { collection: schema.collection, fields: schema.fields, required: schema.required || [] },
    rules: rule,
    indexes,
  };
}

// ---- MongoDB --------------------------------------------------------------
function toMongo(schema) {
  // mongoose is Node-only — we emit DEFINITION SOURCE (a string) plus a portable
  // $jsonSchema validator and index specs the Atlas Data API/back-end can apply.
  const defLines = Object.entries(schema.fields).map(([name, type]) => {
    const mt = MONGOOSE[type] || 'String';
    const idx = (schema.indexes || []).includes(name) ? ', index: true' : '';
    const uniq = name === schema.primaryKey ? ', unique: true' : '';
    return `  ${name}: { type: ${mt}${idx}${uniq} }`;
  });
  const mongooseDefinition =
    `// generated by SchemaCompiler — collection: ${schema.collection}\n` +
    `const ${schema.collection}Schema = new mongoose.Schema({\n${defLines.join(',\n')}\n}, { collection: '${schema.collection}', strict: false });`;

  const properties = {};
  Object.entries(schema.fields).forEach(([name, type]) => { properties[name] = { bsonType: BSON[type] || 'string' }; });
  const jsonSchema = {
    $jsonSchema: {
      bsonType: 'object',
      required: schema.required || [],
      properties,
    },
  };
  const indexes = [
    { key: { [schema.primaryKey]: 1 }, name: `${schema.primaryKey}_unique`, unique: true },
    ...(schema.indexes || []).map((f) => ({ key: { [f]: 1 }, name: `${f}_idx` })),
  ];
  return { provider: 'mongodb', collection: schema.collection, mongooseDefinition, jsonSchema, indexes };
}

// ---- Local ----------------------------------------------------------------
function toLocal(schema) {
  return {
    provider: 'local',
    collection: schema.collection,
    init: { collection: schema.collection, fields: Object.keys(schema.fields), defaults: schema.defaults || {} },
  };
}

// ---- System infrastructure SQL (emitted before user DDL) ------------------
function systemSql(provider) {
  if (provider !== 'supabase') return null;
  return [
    '-- ============================================================',
    '-- SYSTEM INFRASTRUCTURE + SECURITY',
    '-- ============================================================',
    '',
    '-- ============================================================',
    '-- 1. ROLE-BASED ACCESS CONTROL',
    '-- ============================================================',
    '',
    '-- lexai_admin — full DDL + DML + grant authority',
    '-- lexai_manager — DML (CRUD) on all tables, execute functions',
    '-- lexai_user  — read-only + execute specific functions',
    '',
    'do $$ begin',
    '  if not exists (select from pg_roles where rolname = \'lexai_admin\') then',
    '    create role lexai_admin;',
    '  end if;',
    '  if not exists (select from pg_roles where rolname = \'lexai_manager\') then',
    '    create role lexai_manager;',
    '  end if;',
    '  if not exists (select from pg_roles where rolname = \'lexai_user\') then',
    '    create role lexai_user;',
    '  end if;',
    'end $$;',
    '',
    '-- ============================================================',
    '-- 2. exec_sql — hardened DDL execution (ADMIN ONLY)',
    '-- ============================================================',
    '-- exec_sql RPC — allows browser clients to execute DDL via PostgREST.',
    '-- GRANTED ONLY to lexai_admin (never to anon or authenticated).',
    '-- The safe_ddl wrapper below restricts which statements are allowed.',
    '',
    'create or replace function exec_sql(sql text)',
    'returns void',
    'language plpgsql',
    'security definer',
    'as $$',
    'begin',
    '  execute sql;',
    'end;',
    '$$;',
    '',
    '-- safe_ddl — allowlisted DDL execution for managers',
    '-- Only permits CREATE TABLE IF NOT EXISTS, ALTER TABLE ADD COLUMN IF NOT EXISTS,',
    '-- CREATE INDEX IF NOT EXISTS, CREATE OR REPLACE FUNCTION.',
    '-- Blocks DROP, TRUNCATE, ALTER TABLE DROP, GRANT, REVOKE.',
    'create or replace function safe_ddl(sql text)',
    'returns void',
    'language plpgsql',
    'security definer',
    'as $$',
    'declare',
    '  v_upper text;',
    'begin',
    '  v_upper := upper(sql);',
    '  if v_upper ~ \'^\\\\s*DROP\s+(DATABASE|SCHEMA|TABLE|VIEW|FUNCTION|INDEX|ROLE|POLICY)\' then',
    '    raise exception \'safe_ddl: DROP is not permitted\';',
    '  end if;',
    '  if v_upper ~ \'^\\\\s*TRUNCATE\' then',
    '    raise exception \'safe_ddl: TRUNCATE is not permitted\';',
    '  end if;',
    '  if v_upper ~ \'ALTER\s+TABLE.*DROP\s+(COLUMN|CONSTRAINT)\' then',
    '    raise exception \'safe_ddl: ALTER TABLE DROP is not permitted\';',
    '  end if;',
    '  if v_upper ~ \'^\\\\s*(GRANT|REVOKE)\' then',
    '    raise exception \'safe_ddl: GRANT/REVOKE is not permitted\';',
    '  end if;',
    '  if v_upper ~ \'^\\\\s*(DELETE|UPDATE|INSERT|TRUNCATE)\s\' then',
    '    raise exception \'safe_ddl: DML statements are not permitted; use CRUD APIs\';',
    '  end if;',
    '  execute sql;',
    'end;',
    '$$;',
    '',
    'grant execute on function exec_sql(text) to lexai_admin;',
    'grant execute on function safe_ddl(text) to lexai_manager;',
    '',
    '-- ============================================================',
    '-- 3. REGISTRY TABLES',
    '-- ============================================================',
    '',
    '-- schema_registry — tracks schema versions & migrations applied',
    'create table if not exists schema_registry (',
    '  id text primary key default gen_random_uuid()::text,',
    '  version integer not null default 0,',
    '  description text,',
    '  checksum text,',
    '  applied_at timestamptz default now(),',
    '  applied_by text default current_user',
    ');',
    '',
    '-- entity_registry — registered entity definitions',
    'create table if not exists entity_registry (',
    '  id text primary key default gen_random_uuid()::text,',
    '  name text not null unique,',
    '  label text,',
    '  table_name text not null,',
    '  primary_key text default \'id\',',
    '  core boolean default false,',
    '  fields jsonb default \'{}\'::jsonb,',
    '  indexes jsonb default \'{}\'::jsonb,',
    '  created_at timestamptz default now(),',
    '  updated_at timestamptz default now()',
    ');',
    '',
    '-- field_registry — field-level metadata per entity',
    'create table if not exists field_registry (',
    '  id text primary key default gen_random_uuid()::text,',
    '  entity text not null,',
    '  field_name text not null,',
    '  field_type text not null,',
    '  required boolean default false,',
    '  unique_field boolean default false,',
    '  default_value text,',
    '  created_at timestamptz default now()',
    ');',
    '',
    '-- provider_registry — database provider configuration',
    'create table if not exists provider_registry (',
    '  id text primary key default gen_random_uuid()::text,',
    '  provider_type text not null,',
    '  label text,',
    '  config jsonb default \'{}\'::jsonb,',
    '  active boolean default true,',
    '  connected_at timestamptz,',
    '  created_at timestamptz default now(),',
    '  updated_at timestamptz default now()',
    ');',
    '',
    '-- migration_registry — audit log of all schema migrations',
    'create table if not exists migration_registry (',
    '  id text primary key default gen_random_uuid()::text,',
    '  version integer not null,',
    '  description text,',
    '  sql_hash text,',
    '  applied_at timestamptz default now(),',
    '  duration_ms integer,',
    '  success boolean default true,',
    '  error text',
    ');',
    '',
    '-- installer_state — instantaneous installation tracking',
    'create table if not exists installer_state (',
    '  id text primary key default \'default\',',
    '  install_status text not null default \'none\' check (install_status in (\'none\', \'in_progress\', \'completed\', \'failed\')),',
    '  schema_version integer not null default 0,',
    '  installer_version integer not null default 1,',
    '  provider text,',
    '  database_type text,',
    '  verified_at timestamptz,',
    '  installed_at timestamptz,',
    '  updated_at timestamptz default now()',
    ');',
    '',
    '-- ============================================================',
    '-- 4. SCHEMA MAPPING (Priority 2)',
    '-- ============================================================',
    '',
    '-- schema_mapping — LexAI entity name ↔ provider table name',
    'create table if not exists schema_mapping (',
    '  id text primary key default gen_random_uuid()::text,',
    '  entity_name text not null unique,',
    '  provider_table text not null,',
    '  description text,',
    '  active boolean default true,',
    '  version integer not null default 1,',
    '  created_at timestamptz default now(),',
    '  updated_at timestamptz default now()',
    ');',
    '',
    '-- mapping_history — audit log of mapping changes',
    'create table if not exists mapping_history (',
    '  id text primary key default gen_random_uuid()::text,',
    '  entity_name text not null,',
    '  old_table text,',
    '  new_table text not null,',
    '  changed_by text,',
    '  change_reason text,',
    '  created_at timestamptz default now()',
    ');',
    '',
    '-- mapping_versions — versioned snapshots of the entire mapping set',
    'create table if not exists mapping_versions (',
    '  id text primary key default gen_random_uuid()::text,',
    '  version integer not null,',
    '  snapshot jsonb not null,',
    '  description text,',
    '  created_at timestamptz default now()',
    ');',
    '',
    '-- provider_capabilities (Priority 3) — feature detection per provider',
    'create table if not exists provider_capabilities (',
    '  id text primary key default gen_random_uuid()::text,',
    '  provider text not null,',
    '  feature text not null,',
    '  supported boolean not null default false,',
    '  metadata jsonb default \'{}\'::jsonb,',
    '  detected_at timestamptz default now()',
    ');',
    '',
    '-- entity_prefix_registry (Priority 4) — LX-ID prefix management',
    'create table if not exists entity_prefix_registry (',
    '  entity text primary key,',
    '  prefix text not null,',
    '  label text,',
    '  padding integer not null default 5,',
    '  current_sequence integer not null default 0,',
    '  created_at timestamptz default now(),',
    '  updated_at timestamptz default now()',
    ');',
    '',
    '-- ============================================================',
    '-- 5. LX-ID SEQUENCE MANAGER (Priority 4)',
    '-- ============================================================',
    '-- Generates LX-{PREFIX}-{SEQUENCE} using the entity_prefix_registry',
    '-- Example: LX-USR-00001, LX-CASE-00042, LX-DOC-00007',
    '',
    'create or replace function next_lx_id(p_entity text)',
    'returns text',
    'language plpgsql',
    'as $$',
    'declare',
    '  v_prefix text;',
    '  v_pad int;',
    '  v_seq int;',
    '  v_id text;',
    'begin',
    '  -- Ensure prefix entry exists (fallback to uppercase entity)',
    '  insert into entity_prefix_registry (entity, prefix, label, padding, current_sequence)',
    '  values (p_entity, upper(substr(p_entity, 1, 5)), p_entity, 5, 0)',
    '  on conflict (entity) do nothing;',
    '  -- Fetch prefix + padding',
    '  select prefix, padding into strict v_prefix, v_pad from entity_prefix_registry where entity = p_entity;',
    '  -- Increment sequence',
    '  update entity_prefix_registry',
    '  set current_sequence = current_sequence + 1,',
    '      updated_at = now()',
    '  where entity = p_entity',
    '  returning current_sequence into v_seq;',
    '  -- Build LX-PREFIX-SEQ',
    '  v_id := \'LX-\' || v_prefix || \'-\' || lpad(v_seq::text, v_pad, \'0\');',
    '  return v_id;',
    'end;',
    '$$;',
    '',
    '-- Also keep id_registry for backward compatibility',
    'create table if not exists id_registry (',
    '  entity text primary key,',
    '  prefix text not null,',
    '  sequence integer not null default 0,',
    '  created_at timestamptz default now(),',
    '  updated_at timestamptz default now()',
    ');',
    '',
    '-- ============================================================',
    '-- 6. FOREIGN KEY MIGRATION SUPPORT (Priority 5)',
    '-- ============================================================',
    '',
    '-- foreign_key_registry — tracks FK relationships across entities',
    'create table if not exists foreign_key_registry (',
    '  id text primary key default gen_random_uuid()::text,',
    '  from_entity text not null,',
    '  from_field text not null,',
    '  to_entity text not null,',
    '  to_field text not null default \'id\',',
    '  cascade_delete boolean default false,',
    '  enabled boolean default true,',
    '  created_at timestamptz default now()',
    ');',
    '',
    '-- FK migration: case-related entities cascade with cases',
    'alter table reminders add constraint fk_reminders_case_id foreign key ("caseId") references cases (id) on delete cascade;',
    'alter table notes add constraint fk_notes_case_id foreign key ("caseId") references cases (id) on delete cascade;',
    'alter table hearings add constraint fk_hearings_case_id foreign key ("caseId") references cases (id) on delete cascade;',
    'alter table drafts add constraint fk_drafts_case_id foreign key ("caseId") references cases (id) on delete cascade;',
    'alter table documents add constraint fk_documents_case_id foreign key ("caseId") references cases (id) on delete cascade;',
    'alter table "caseHistory" add constraint fk_case_history_case_id foreign key ("caseId") references cases (id) on delete cascade;',
    'alter table "caseFolders" add constraint fk_case_folders_case_id foreign key ("caseId") references cases (id) on delete cascade;',
    'alter table "caseActivity" add constraint fk_case_activity_case_id foreign key ("caseId") references cases (id) on delete cascade;',
    '',
    '-- FK migration: audit trail references users (keep on delete)',
    'alter table "auditLogs" add constraint fk_audit_logs_user_id foreign key ("userId") references users (id) on delete set null;',
    '',
    '-- FK migration: role reference (prevent deletion of active roles)',
    'alter table users add constraint fk_users_role_code foreign key ("roleCode") references roles (code) on delete restrict;',
    '',
    '-- FK migration: folder parent (self-referencing cascade)',
    'alter table "caseFolders" add constraint fk_case_folders_parent_id foreign key ("parentId") references "caseFolders" (id) on delete cascade;',
    '',
    '-- ============================================================',
    '-- 7. ROW LEVEL SECURITY',
    '-- ============================================================',
    '-- Enable RLS on all registry tables',
    'alter table if exists schema_registry enable row level security;',
    'alter table if exists entity_registry enable row level security;',
    'alter table if exists field_registry enable row level security;',
    'alter table if exists provider_registry enable row level security;',
    'alter table if exists migration_registry enable row level security;',
    'alter table if exists installer_state enable row level security;',
    'alter table if exists schema_mapping enable row level security;',
    'alter table if exists mapping_history enable row level security;',
    'alter table if exists mapping_versions enable row level security;',
    'alter table if exists provider_capabilities enable row level security;',
    'alter table if exists entity_prefix_registry enable row level security;',
    'alter table if exists id_registry enable row level security;',
    'alter table if exists foreign_key_registry enable row level security;',
    '',
    '-- ============================================================',
    '-- 8. RLS POLICIES',
    '-- ============================================================',
    '',
    '-- lexai_admin: full access to all tables',
    'create policy admin_all on schema_registry for all to lexai_admin using (true) with check (true);',
    'create policy admin_all on entity_registry for all to lexai_admin using (true) with check (true);',
    'create policy admin_all on field_registry for all to lexai_admin using (true) with check (true);',
    'create policy admin_all on provider_registry for all to lexai_admin using (true) with check (true);',
    'create policy admin_all on migration_registry for all to lexai_admin using (true) with check (true);',
    'create policy admin_all on installer_state for all to lexai_admin using (true) with check (true);',
    'create policy admin_all on schema_mapping for all to lexai_admin using (true) with check (true);',
    'create policy admin_all on mapping_history for all to lexai_admin using (true) with check (true);',
    'create policy admin_all on mapping_versions for all to lexai_admin using (true) with check (true);',
    'create policy admin_all on provider_capabilities for all to lexai_admin using (true) with check (true);',
    'create policy admin_all on entity_prefix_registry for all to lexai_admin using (true) with check (true);',
    'create policy admin_all on id_registry for all to lexai_admin using (true) with check (true);',
    'create policy admin_all on foreign_key_registry for all to lexai_admin using (true) with check (true);',
    '',
    '-- lexai_manager: read + write (but not DDL) on registry tables',
    'create policy manager_read on schema_registry for select to lexai_manager using (true);',
    'create policy manager_read on entity_registry for select to lexai_manager using (true);',
    'create policy manager_write on entity_registry for insert to lexai_manager with check (true);',
    'create policy manager_write on entity_registry for update to lexai_manager using (true);',
    'create policy manager_read on field_registry for select to lexai_manager using (true);',
    'create policy manager_write on field_registry for insert to lexai_manager with check (true);',
    'create policy manager_read on provider_registry for select to lexai_manager using (true);',
    'create policy manager_read on migration_registry for select to lexai_manager using (true);',
    'create policy manager_read on installer_state for select to lexai_manager using (true);',
    'create policy manager_read on schema_mapping for select to lexai_manager using (true);',
    'create policy manager_write on schema_mapping for insert to lexai_manager with check (true);',
    'create policy manager_write on schema_mapping for update to lexai_manager using (true);',
    'create policy manager_read on mapping_history for select to lexai_manager using (true);',
    'create policy manager_read on mapping_versions for select to lexai_manager using (true);',
    'create policy manager_read on provider_capabilities for select to lexai_manager using (true);',
    'create policy manager_read on entity_prefix_registry for select to lexai_manager using (true);',
    'create policy manager_read on id_registry for select to lexai_manager using (true);',
    'create policy manager_read on foreign_key_registry for select to lexai_manager using (true);',
    '',
    '-- lexai_user: read-only on non-sensitive registry tables',
    'create policy user_read on schema_registry for select to lexai_user using (true);',
    'create policy user_read on entity_registry for select to lexai_user using (true);',
    'create policy user_read on field_registry for select to lexai_user using (true);',
    'create policy user_read on installer_state for select to lexai_user using (true);',
    'create policy user_read on provider_capabilities for select to lexai_user using (true);',
    '',
    '-- ============================================================',
    '-- 9. INDEXES',
    '-- ============================================================',
    'create index if not exists idx_field_registry_entity on field_registry (entity);',
    'create index if not exists idx_schema_registry_version on schema_registry (version);',
    'create index if not exists idx_migration_registry_version on migration_registry (version);',
    'create index if not exists idx_migration_registry_applied_at on migration_registry (applied_at);',
    'create index if not exists idx_provider_registry_active on provider_registry (active);',
    'create index if not exists idx_schema_mapping_active on schema_mapping (active);',
    'create index if not exists idx_mapping_history_entity on mapping_history (entity_name);',
    'create index if not exists idx_provider_capabilities_provider on provider_capabilities (provider);',
    'create index if not exists idx_provider_capabilities_feature on provider_capabilities (feature);',
    'create index if not exists idx_entity_prefix_registry_prefix on entity_prefix_registry (prefix);',
    'create index if not exists idx_foreign_key_registry_from on foreign_key_registry (from_entity);',
    'create index if not exists idx_foreign_key_registry_to on foreign_key_registry (to_entity);',
  ].join('\n');
}

const COMPILERS = { supabase: toSupabase, firebase: toFirebase, mongodb: toMongo, local: toLocal };

export const SchemaCompiler = {
  // Compile one schema (by name or descriptor) for a provider.
  compile(provider, schemaOrName) {
    const schema = typeof schemaOrName === 'string' ? getSchema(schemaOrName) : schemaOrName;
    if (!schema) throw new Error(`Unknown schema: ${schemaOrName}`);
    const fn = COMPILERS[provider] || COMPILERS.local;
    return fn(schema);
  },

  // Compile every schema for a provider.
  compileAll(provider) {
    return listSchemas().map((s) => this.compile(provider, s));
  },

  // A single install script/bundle for a provider.
  installArtifact(provider) {
    const parts = this.compileAll(provider);
    if (provider === 'supabase') {
      const infra = systemSql(provider);
      const ddl = parts.map((p) => p.sql).join('\n\n');
      const grants = [
        '-- ============================================================',
        '-- 10. LEAST-PRIVILEGE GRANTS',
        '-- ============================================================',
        '-- lexai_admin inherits from the built-in superuser-like role;',
        '-- it owns all objects. No explicit grants needed — admin bypasses RLS.',
        '',
        '-- lexai_manager: schema usage + CRUD on user tables',
        'GRANT USAGE ON SCHEMA public TO lexai_manager;',
        'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO lexai_manager;',
        'GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO lexai_manager;',
        '',
        '-- lexai_user: read-only on user tables',
        'GRANT USAGE ON SCHEMA public TO lexai_user;',
        'GRANT SELECT ON ALL TABLES IN SCHEMA public TO lexai_user;',
        '',
        '-- future tables inherit grants automatically',
        'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO lexai_manager;',
        'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO lexai_user;',
        'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO lexai_manager;',
      ].join('\n');
      return { kind: 'sql', schemaVersion: SCHEMA_VERSION, text: [infra, ddl, grants].join('\n\n') };
    }
    if (provider === 'firebase') {
      return {
        kind: 'firebase',
        schemaVersion: SCHEMA_VERSION,
        rules: `rules_version = '2';\nservice cloud.firestore {\n  match /databases/{database}/documents {\n${parts.map((p) => p.rules).join('\n')}\n  }\n}`,
        indexes: { indexes: parts.flatMap((p) => p.indexes) },
      };
    }
    if (provider === 'mongodb') {
      return {
        kind: 'mongodb',
        schemaVersion: SCHEMA_VERSION,
        mongoose: parts.map((p) => p.mongooseDefinition).join('\n\n'),
        validators: Object.fromEntries(parts.map((p) => [p.collection, p.jsonSchema])),
        indexes: Object.fromEntries(parts.map((p) => [p.collection, p.indexes])),
      };
    }
    return { kind: 'local', schemaVersion: SCHEMA_VERSION, collections: parts.map((p) => p.init) };
  },
};

export default SchemaCompiler;
